"""add execution traces and token budget columns

Revision ID: f18203ae8cf8
Revises: 9af908d04c01
Create Date: 2026-09-19 19:50:29.419391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18203ae8cf8'
down_revision: Union[str, Sequence[str], None] = '9af908d04c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_traces_run_id', 'execution_traces', ['run_id'], unique=False)
    # server_default backfills existing rows (research_runs is not empty in
    # every environment); the model's Python-side default covers new rows
    # going forward, so the server_default is dropped right after.
    op.add_column(
        'research_runs',
        sa.Column('total_tokens_used', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'research_runs',
        sa.Column('budget_exceeded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('research_runs', 'total_tokens_used', server_default=None)
    op.alter_column('research_runs', 'budget_exceeded', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'budget_exceeded')
    op.drop_column('research_runs', 'total_tokens_used')
    op.drop_index('ix_execution_traces_run_id', table_name='execution_traces')
    op.drop_table('execution_traces')
    # ### end Alembic commands ###
